version: 2
jobs:

  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      SCRATCH: "/scratch"
    docker:
      - image: docker:18.06.1-ce-git
    resource_class: large
    working_directory: /tmp/src/qsiprep_build
    steps:
      - checkout
      - run:
          name: Install parallel gzip and python3
          command: |
            apk add --no-cache pigz python3 tar
      - restore_cache:
          keys:
            - docker-v10-{{ .Branch }}-{{ .Revision }}
            - docker-v10-{{ .Branch }}-
            - docker-v10-main-
            - docker-v10-
          paths:
            - /tmp/cache/docker.tar.gz
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Build Docker image
          no_output_timeout: 4h
          command: |
            # Get version, update files
            e=1 && for i in {1..5}; do
              docker build \
                --cache-from=pennbbl/qsiprep_build \
                --rm=false \
                -t pennbbl/qsiprep_build:latest
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]

      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save nvidia/cuda:9.1-runtime-ubuntu16.04 pennbbl/qsiprep_build:latest \
            | pigz -3 > /tmp/cache/docker.tar.gz

      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag pennbbl/qsiprep_build pennbbl/qsiprep_build:unstable
              docker push pennbbl/qsiprep_build:unstable
              if [[ -n "$CIRCLE_TAG" ]]; then
                docker push pennbbl/qsiprep_build:latest
                docker tag pennbbl/qsiprep_build pennbbl/qsiprep_build:$CIRCLE_TAG
                docker push pennbbl/qsiprep_build_build:$CIRCLE_TAG
              fi
            fi

      - persist_to_workspace:
          root: /tmp
          paths:
            - src/qsiprep_build

      - save_cache:
         key: docker-v10-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
         paths:
           - /tmp/cache/docker.tar.gz


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/