version: 2
jobs:

  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      SCRATCH: "/scratch"
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: /tmp/src/qsiprep_build
    steps:
      - checkout
      - run:
          name: Install parallel gzip and python3
          command: |
            apk add --no-cache python3 tar
      - setup_remote_docker

      - run:
          name: Build Docker image
          no_output_timeout: 5h
          command: |
              docker build \
                --rm=false \
                -t pennbbl/qsiprep_build:latest .

      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 1h
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              if [[ -n "$CIRCLE_TAG" ]]; then
                docker push pennbbl/qsiprep_build:latest
                docker tag pennbbl/qsiprep_build pennbbl/qsiprep_build:$CIRCLE_TAG
                docker push pennbbl/qsiprep_build:$CIRCLE_TAG
              fi
            fi


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/